version: '3.9'
services:
  ps-server:
    command: python ps_server.py 
    ports:
      - 50051:50051
    image: icesat2sliderule/sliderule-ps-server-test-stub:${PS_SERVER_DOCKER_TAG}
    container_name: ps-server
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_SESSION_TOKEN=test
  ps-db:
    image: postgres:13
    container_name: ps-db
    volumes:
      - postgres_data_v4:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - ./temp_redis_data:/data
  django-app:
    env_file:
      - .env
    expose:
      - 8000
    image: ${DOCKER_REPO}/sliderule-ps-web:${PS_WEB_DOCKER_TAG}
    container_name: ps-web
    volumes:
      - ./users/migrations:/home/reg_user/ps/users/migrations
      - ./api/migrations:/home/reg_user/ps/api/migrations
      - ${PWD}/api/schema:/home/reg_user/ps/api/schema
      - ~/.aws/:/home/reg_user/.aws/
      - ./htmlcov:/home/reg_user/ps/htmlcov
      - .coveragerc:/home/reg_user/ps/.coveragerc

    depends_on:
      - ps-db
      - redis
      - ps-server
  nginx:
    image: ${DOCKER_REPO}/sliderule-ps-nginx:${PS_NGINX_DOCKER_TAG}
    container_name: ps-nginx
    ports:
      - 80:80
    depends_on:
      - django-app
volumes:
  postgres_data_v4:
networks:
  default:
    name: ps_dev_network
